name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    env:
      python_ver: '3.10'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python_ver }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_ver }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt
          pip install -r ./requirements.txt -t ./lib
      - name: Create package
        run: |
          $exclude = @('.git', '.github', 'poetry.lock', 'pyproject.toml', '.venv', 'test.py')
          $items = Get-ChildItem -Path . -Force | Where-Object { $exclude -notcontains $_.Name } | ForEach-Object { $_.FullName }
          Compress-Archive -Path $items -DestinationPath ShinnkuGalgamePlugin.zip -Force
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: 'ShinnkuGalgamePlugin.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}